extends: ../configs/default.yaml

runtime:
  python_bin: python3

paths:
  workspace_root: /workspace-data/talkvid
  log_folder: /workspace-data/talkvid/logs

cookies:
  files:
    - /workspace-data/secrets/youtube_chrome_cookies.txt
    - /workspace-data/secrets/youtube_safari_cookies.txt
  from_browser: ""
